SELECT * EXCLUDE(C_COMMENT,N_COMMENT,R_COMMENT)
FROM {{ref('STG_CUSTOMER')}} C
INNER JOIN {{ref('STG_NATION')}} N
ON C.C_NATIONKEY=N_NATIONKEY
INNER JOIN {{ref('STG_REGION')}}  R
ON N.N_REGIONKEY=R.R_REGIONKEY