version: 2

sources:
  - name: raw
    database: DBT_DB           # your Snowflake database
    schema: RAWLAYER           # schema where 'orders' table exists
    tables:
      - name: orders
