version: 2

sources:
  - name: snowflake_sample_data           # this is the source name used in your model
    database: SNOWFLAKE_SAMPLE_DATA    # the database where the table exists
    schema: TPCH_SF1  # the schema where the table exists
    description: "Raw source tables"
    tables:
      - name: orders     # the table name used in your model
        description: "Orders table from raw source"
